version: 2.1

parameters:
  workflow-filter-based-only-on-parameters:
    type: boolean
    default: false
    
jobs:
  myjob:
    docker:
      - image: cimg/node:17.9.1
    steps:
      - checkout
      - run:
          name: cat README
          command: cat README.md
      - run:
          name: echo
          command: echo "no op"

workflows:
  do_some_stuff:
    jobs:
      - myjob

